### ISSUE TITLE
leader 键如何使用？

### ISSUE THREAD

**Issue by ageovb** [soluty/sui#1]
目前在用 SpaceFn 脚本，按住 Space 键再按其他键触发，不知道本项目的是否也是如此？

leader 键是哪个按键？怎么使用的？

**Comment by soluty** [comment]
leader键是相对sui的软件分类的概念的, sui将软件分成几类
例如: 窗口管理器的leader是ctrl  leader+y 代表按住ctrl+y 
终端或者浏览器的leader是ctrl+alt
终端多路复用器的leader是alt
普通gui软件的leader是alt
普通cli或者tui软件的leader是  , 或者没有 leader
