### ISSUE TITLE
不支持的16位应用程序

### ISSUE THREAD

**Issue by 00110100** [soluty/sui#2]
win11下执行install.bat报错
![image](https://github.com/soluty/sui/assets/27733124/0530263a-ef06-4fd8-b505-22fc51ea8b2d)，请问怎么解决

**Comment by soluty** [comment]
我现在没有用win11,  你如果会用golang的话,  可以自己编译sui/layoutchanger目录下面的main.go文件. 我需要安装一个win11的虚拟机来检查到底出了什么问题或者你加我qq 15925754, 远程让我编译一份. 理论上我是在win10上用golang编译的二进制应该是可以直接用在win11上的, 不知道为啥win11上用不了.

**Comment by kaluosifa** [comment]
Win10 下也报了一样的错误，还有这个
![image](https://github.com/soluty/sui/assets/41535519/4c06e22a-6699-42f8-80f5-3ab199df9f7b)

**Comment by soluty** [comment]
我找到原因了, 我会录制一个视频详细的说明一下这个问题.

**Comment by soluty** [comment]
已经fix掉了, 原因是不通过git clone直接 download zip引起的, 这样会导致我用的git-lfs存储的exe不能用, 现在没用git-lfs管理exe文件.
详细的安装视频说明在 https://www.bilibili.com/video/BV1s64y1n7R6/
